stages:
  - build
  - deploy
variables:
  PROJECT_NAME: "pfe20243"
  IMAGE_NAME: "fast-api-test-project"
  DOCKER_TAG: "latest"

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG" .
    - docker push "$CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG"
  tags:
    - docker-runner

deploy:
  stage: deploy
  before_script:
    - echo "Pulling Docker image from registry..."
    - ssh root@192.168.1.131 "docker pull registry.gitlab.com/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG"
    - echo "Stopping and removing existing containers..."
    - ssh root@192.168.1.131 "docker-compose -f /root/wassim/training/myprojectfastapi/fast-Api-Test-Project/ down"
  script:
    - ssh root@192.168.1.131 "docker-compose -f /root/wassim/training/myprojectfastapi/fast-Api-Test-Project/ up -d"
  tags:
    - ssh-runner-b

# stages:
#   - test

# test:
#   stage: test
#   script:
#     - echo "Testing SSH connection"
#     - ssh root@192.168.1.131 "echo 'SSH connection successful'"
#     - docker ps
#   tags:
#     - ssh-runner-b