stages:
  - test
  - build

variables:
  POSTGRES_DB: fastapi
  POSTGRES_USER: fastapi
  POSTGRES_PASSWORD: fastapi

services:
  - name: postgres:12.1-alpine
    alias: db

test:
  stage: test
  image: python:3.8.1-alpine
  before_script:
    - pip install -r requirements.txt || true
  script:
    - pytest

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t registry.gitlab.com/pfe20243/fast-api-test-project .
    - docker push registry.gitlab.com/pfe20243/fast-api-test-project
