stages:
  - build
  - deploy

variables:
  PROJECT_NAME: "pfe20243"
  IMAGE_NAME: "fast-api-test-project"

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - DOCKER_TAG=$(echo "$CI_COMMIT_SHA" | cut -c1-8)  # Use first 8 characters of commit hash as tag
    - docker build -t "$CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG" .
    - docker push "$CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG"
  tags:
    - docker-runner-cb

deploy:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - echo "Deleting existing Docker image from registry..."
    - DOCKER_TAG=$(echo "$CI_COMMIT_SHA" | cut -c1-8)  # Ensure using the latest commit SHA as tag
    - ssh root@192.168.1.131 "docker image rm $CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG || true"  # Ignore error if image doesn't exist
  script:
    - echo "Rebuilding and pulling Docker image..."
    - DOCKER_TAG=$(echo "$CI_COMMIT_SHA" | cut -c1-8)  # Ensure using the latest commit SHA as tag
    - docker pull "$CI_REGISTRY/$PROJECT_NAME/$IMAGE_NAME:$DOCKER_TAG"
    - echo "Stopping and removing existing containers..."
    - ssh root@192.168.1.131 "docker-compose -f /root/wassim/training/myprojectfastapi/fast-Api-Test-Project/docker-compose.yml down"
    - echo "Starting the updated container..."
    - ssh root@192.168.1.131 "docker-compose -f /root/wassim/training/myprojectfastapi/fast-Api-Test-Project/docker-compose.yml up -d"
  tags:
    - ssh-runner-b
