stages:
  - test
  - build

variables:
  POSTGRES_DB: fastapi
  POSTGRES_USER: fastapi
  POSTGRES_PASSWORD: fastapi

services:
  - name: postgres:12.1-alpine
    alias: db

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - pip install --no-binary uvloop --no-binary httptools -r requirements.txt
    - docker build -t registry.gitlab.com/pfe20243/fast-api-test-project .
    - docker push registry.gitlab.com/pfe20243/fast-api-test-project
  tags:
    - docker-runner
