stages:
  - build
  - deploy

build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u bvssel -p glpat-k_wnu8uVfGwF8VGGPX6y registry.gitlab.com
    - export PYTHONPATH=/src
  script:
    - docker build -t registry.gitlab.com/pfe20243/fast-api-test-project .
    - docker push registry.gitlab.com/pfe20243/fast-api-test-project
    - echo "Directory structure:"
    - ls -la
    - echo $PYTHONPATH
  tags:
    - docker-runner

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker-compose down
    - echo "helloooooooooooooooooo"
    - docker-compose run --rm app ls /src
  script:
    - docker-compose up -d
  tags:
    - docker-runner

# 
# stages:
#   - build
#   - deploy

# build:
#   stage: build
#   image: docker:19.03.12
#   services:
#     - docker:19.03.12-dind
#   before_script:
#     - docker login -u bvssel -p glpat-k_wnu8uVfGwF8VGGPX6y registry.gitlab.com
#   script:
#     - docker build -t registry.gitlab.com/pfe20243/fast-api-test-project .
#     - docker push registry.gitlab.com/pfe20243/fast-api-test-project
#   tags:
#     - docker-runner

# deploy:
#   stage: deploy
#   image: docker:latest
#   services:
#     - docker:dind
#   before_script:
#     - docker-compose down
#   script:
#     - docker-compose up -d
#   tags:
#     - docker-runner