version: "3.7"

networks:
  mynetwork:

services:
  app:
    image: registry.gitlab.com/pfe20243/fast-api-test-project:latest
    container_name: app
    labels:
      filebeat: "true"
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app
    networks:
      - mynetwork

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat
    user: root
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/wassim/training/myprojectfastapi/ELK-config/filebeat.yml:/usr/share/filebeat/filebeat.yml"
    networks:
      - mynetwork

      
  # nginx:
  #   image: nginx:latest
  #   container_name: nginxcontainer
  #   ports:
  #     - "8888:8888"
  #     - "8443:8443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /root/wassim/certificats/server.crt:/etc/nginx/certs/server.crt
  #     - /root/wassim/certificats/server.key:/etc/nginx/certs/server.key
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - app
