version: "3.7"

networks:
  mynetwork:

services:
  app:
    image: registry.gitlab.com/pfe20243/fast-api-test-project:latest
    container_name: app
    ports:
      - 8001:8000
    networks:
      - mynetwork
      
  nginx:
    image: nginx:latest
    container_name: nginxcontainer
    ports:
      - "8888:8888"
      - "8443:8443"
    volumes:
      - /root/wassim/certificats:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      - mynetwork
    depends_on:
      - app
