version: "3.7"

services:
  app:
    build: .
    container_name: myfastapiapp
    volumes:
      - ./:/src/
    ports:
      - 8002:8000
    # environment:
    #   - DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi