version: "3.7"

networks:
  proxiable:
    name: proxiable
    
services:
  app:
    image: registry.gitlab.com/pfe20243/fast-api-test-project:latest
    container_name: app
    ports:
      - 8001:8000
    networks:
      - proxiable

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 8080:80wewe
  #   volumes:wwewe
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
